// Central tournament setup.
// To trial another event, change this file plus your Vercel env vars:
// SLASH_GOLF_TOURN_ID, SLASH_GOLF_YEAR, TOURNAMENT_STATE_ID.

export const tournamentConfig = {
  majorLabel: '91ST MASTERS TOURNAMENT',
  title: 'MASTERS PICK 3 LIVE',
  venue: 'Augusta National Golf Club',
  location: 'Augusta, Georgia',
  dates: 'April 8–11, 2027',
  prizePool: '$1,800',
  tournamentTimezone: 'America/Chicago',
  jackpotRule: 'To win, your picks must include the Masters Champion. If no punter selects them, the prize pool jackpots.',
  heroImage: '/augusta1.jpg'
};
 
export const poolEntries = [
  { player: 'Sparky', picks: ['Sungjae Im', 'Ryan Gerard', 'Hideki Matsuyama'] },
  { player: 'Roche SES', picks: ['Scottie Scheffler', 'Alex Noren', 'Matt McCarty'] },
  { player: 'Mac The Knife', picks: ['Chris Gotterup', 'Justin Thomas', 'Kurt Kitayama'] },
  { player: 'J Turner', picks: ['Rory McIlroy', 'Michael Brennan', 'Sam Burns'] },
  { player: 'A Rose', picks: ['Maverick McNealy', 'Justin Rose', 'Sepp Straka'] },
  { player: 'Greg B', picks: ['Collin Morikawa', 'Ryan Fox', 'Jacob Bridgeman'] },
  { player: 'Kev Martin', picks: ['Tommy Fleetwood', 'Alex Smalley', 'Bud Cauley'] },
  { player: 'Katie D', picks: ['Xander Schauffele', 'Ryo Hisatsune', 'Matt Fitzpatrick'] },
  { player: 'The Wrangler', picks: ['Ludvig Åberg', 'J.T. Poston', 'Eric Cole'] },
  { player: 'Barty', picks: ['Scottie Scheffler', 'Nicolai Højgaard', 'Michael Thorbjornsen'] },
  { player: 'JB', picks: ['Justin Thomas', 'Robert MacIntyre', 'Min Woo Lee'] },
  { player: 'L Adams', picks: ['Patrick Cantlay', 'Gary Woodland', 'Aaron Rai'] },
  { player: 'P Mac', picks: ['Viktor Hovland', 'Cameron Young', 'Alex Fitzpatrick'] },
  { player: 'JD Boy', picks: ['Rory McIlroy', 'Sam Burns', 'Ryo Hisatsune'] },
  { player: 'Enright', picks: ['Ben Griffin', 'Sungjae Im', 'Kurt Kitayama'] },
  { player: 'Jonesy', picks: ['Tom Kim', 'Matt McCarty', 'Xander Schauffele'] },
  { player: 'Chalkey', picks: ['Hideki Matsuyama', 'Chris Gotterup', 'Nicolai Højgaard'] },
  { player: 'J Tilley', picks: ['Scottie Scheffler', 'Alex Smalley', 'Robert MacIntyre'] },
  { player: 'Spinetto', picks: ['Ludvig Åberg', 'Patrick Cantlay', 'Rickie Fowler'] },
  { player: 'Trump H', picks: ['Justin Rose', 'Michael Brennan', 'Rory McIlroy'] },
  { player: 'Matt B', picks: ['Sepp Straka', 'Matt Fitzpatrick', 'Ryan Gerard'] },
  { player: 'Sloanie', picks: ['Sahith Theegala', 'Maverick McNealy', 'J.J. Spaun'] },
  { player: 'G Ponting', picks: ['Tommy Fleetwood', 'Adam Scott', 'Nico Echavarria'] },
  { player: 'Kimbo Slice', picks: ['Sam Burns', 'Min Woo Lee', 'Michael Thorbjornsen'] },
  { player: 'M Sanders', picks: ['Russell Henley', 'Akshay Bhatia', 'Alex Noren'] },
  { player: 'Bradley C', picks: ['Justin Thomas', 'Wyndham Clark', 'Ryo Hisatsune'] },
  { player: 'Nick Fitz', picks: ['Matt Fitzpatrick', 'Kristoffer Reitan', 'Gary Woodland'] },
  { player: 'P Lund', picks: ['Aaron Rai', 'J.T. Poston', 'Viktor Hovland'] },
  { player: 'Up the Whas', picks: ['Chris Gotterup', 'Rory McIlroy', 'Cameron Young'] },
  { player: 'Mal J', picks: ['Robert MacIntyre', 'Tom Kim', 'Jacob Bridgeman'] },
  { player: 'Shaw', picks: ['Xander Schauffele', 'Sungjae Im', 'Bud Cauley'] },
  { player: 'D Haycock', picks: ['Hideki Matsuyama', 'Ben Griffin', 'Matt McCarty'] },
  { player: 'Maccas', picks: ['Collin Morikawa', 'Sepp Straka', 'Maverick McNealy'] },
  { player: 'Lamming', picks: ['Ryan Fox', 'Nicolai Højgaard', 'Eric Cole'] },
  { player: 'T Rowe', picks: ['Justin Rose', 'Michael Brennan', 'Scottie Scheffler'] },
  { player: 'AD', picks: ['Min Woo Lee', 'Alex Fitzpatrick', 'Chris Gotterup'] },
  { player: 'H Naka', picks: ['Cameron Young', 'Tommy Fleetwood', 'Akshay Bhatia'] },
  { player: 'M Little', picks: ['Rory McIlroy', 'Kurt Kitayama', 'Ryan Gerard'] },
  { player: 'Nath Ferg', picks: ['Sam Burns', 'Alex Smalley', 'Nico Echavarria'] },
  { player: 'Cam P', picks: ['Scottie Scheffler', 'Ryo Hisatsune', 'Michael Thorbjornsen'] },
  { player: 'T Coleman', picks: ['Justin Thomas', 'Ludvig Åberg', 'Bud Cauley'] },
  { player: 'Crusader', picks: ['Tommy Fleetwood', 'Wyndham Clark', 'Matt McCarty'] },
  { player: 'Baylis', picks: ['Justin Rose', 'Russell Henley', 'Jacob Bridgeman'] },
  { player: 'Mr Grant', picks: ['Xander Schauffele', 'Gary Woodland', 'Sahith Theegala'] },
  { player: 'Brian Irish', picks: ['Patrick Cantlay', 'Sepp Straka', 'Michael Brennan'] },
  { player: 'Muzza T', picks: ['Tom Kim', 'Ryan Fox', 'Alex Noren'] },
  { player: 'Pete Holly', picks: ['Viktor Hovland', 'Nicolai Højgaard', 'Chris Gotterup'] },
  { player: 'Timmy S', picks: ['Aaron Rai', 'Maverick McNealy', 'Justin Thomas'] },
  { player: 'Arnie Palmer', picks: ['Scottie Scheffler', 'Rickie Fowler', 'Ryo Hisatsune'] },
  { player: 'K McGinness', picks: ['Collin Morikawa', 'Min Woo Lee', 'Kurt Kitayama'] },
  { player: 'Trent W', picks: ['Ludvig Åberg', 'Ryan Gerard', 'Bud Cauley'] },
  { player: 'Wazza SB', picks: ['Robert MacIntyre', 'Sam Burns', 'Alex Smalley'] },
  { player: 'Sir Steve', picks: ['Rory McIlroy', 'Sungjae Im', 'Michael Thorbjornsen'] },
  { player: 'T Wallace', picks: ['Tommy Fleetwood', 'Akshay Bhatia', 'Matt Fitzpatrick'] },
  { player: 'Hancock', picks: ['Justin Rose', 'Ben Griffin', 'Nico Echavarria'] },
  { player: 'B Ashford', picks: ['Xander Schauffele', 'Jake Knapp', 'Russell Henley'] },
  { player: 'Barley', picks: ['Nicolai Højgaard', 'Chris Gotterup', 'Ryan Fox'] },
  { player: 'Nat M', picks: ['Scottie Scheffler', 'Alex Fitzpatrick', 'Eric Cole'] },
  { player: 'J Barbour', picks: ['Tom Kim', 'Justin Thomas', 'Matt McCarty'] },
  { player: 'Haycock Snr', picks: ['Sahith Theegala', 'Hideki Matsuyama', 'Maverick McNealy'] },
  { player: 'D Donnelly', picks: ['Russell Henley', 'Sepp Straka', 'J.T. Poston'] },
  { player: 'Brom', picks: ['Ryo Hisatsune', 'Robert MacIntyre', 'Michael Brennan'] },
  { player: 'R Fowler', picks: ['Rickie Fowler', 'Sam Burns', 'Kurt Kitayama'] },
  { player: 'Budgie', picks: ['Collin Morikawa', 'Viktor Hovland', 'Jacob Bridgeman'] },
  { player: 'Lynda R', picks: ['Patrick Cantlay', 'Justin Rose', 'Gary Woodland'] },
  { player: 'John Edge', picks: ['Alex Noren', 'Min Woo Lee', 'Wyndham Clark'] },
  { player: 'P Langley', picks: ['Robert MacIntyre', 'Ludvig Åberg', 'Aaron Rai'] },
  { player: 'A Bull', picks: ['Nico Echavarria', 'Rory McIlroy', 'Bud Cauley'] },
  { player: 'D Tucker', picks: ['Maverick McNealy', 'Tommy Fleetwood', 'Michael Thorbjornsen'] },
  { player: 'D McCarthy', picks: ['Chris Gotterup', 'Sungjae Im', 'Xander Schauffele'] },
  { player: 'Mr Manson', picks: ['Matt Fitzpatrick', 'Ryan Fox', 'J.J. Spaun'] },
  { player: 'R McKnight', picks: ['Sepp Straka', 'Viktor Hovland', 'Gary Woodland'] },
  { player: 'Kitch', picks: ['Rory McIlroy', 'Tom Kim', 'Alex Smalley'] },
  { player: 'Doc Campbell', picks: ['Justin Thomas', 'Hideki Matsuyama', 'Ryan Gerard'] },
  { player: 'K Ferg', picks: ['Justin Rose', 'Min Woo Lee', 'Russell Henley'] },
];
