// Central tournament setup.
// To trial another event, change this file plus your Vercel env vars:
// SLASH_GOLF_TOURN_ID, SLASH_GOLF_YEAR, TOURNAMENT_STATE_ID.

export const tournamentConfig = {
  majorLabel: '91ST MASTERS TOURNAMENT',
  title: 'MASTERS PICK 3 LIVE',
  venue: 'Augusta National Golf Club',
  location: 'Augusta, Georgia',
  dates: 'April 8–11, 2027',
  prizePool: '$1,800',
  tournamentTimezone: 'America/Chicago',
  jackpotRule: 'To win, your picks must include the Masters Champion. If no punter selects them, the prize pool jackpots.',
  heroImage: '/augusta.jpg'
};
 
export const poolEntries = [
  { player: 'Sparky', picks: ['Aaron Rai', 'Tommy Fleetwood', 'Rory McIlroy'] },
  { player: 'Roche SES', picks: ['Cameron Young', 'Tommy Fleetwood', 'Rory McIlroy'] },
  { player: 'Mac The Knife', picks: ['Cameron Young', 'Kristoffer Reitan', 'Sepp Straka'] },
  { player: 'J Turner', picks: ['Sam Burns', 'Scottie Scheffler', 'Ludvig Åberg'] },
  { player: 'A Rose', picks: ['Scottie Scheffler', 'Tommy Fleetwood', 'Justin Rose'] },
  { player: 'Greg B', picks: ['Tommy Fleetwood', 'Ludvig Åberg', 'Rory McIlroy'] },
  { player: 'Kev Martin', picks: ['Tommy Fleetwood', 'Ludvig Åberg', 'Rory McIlroy'] },
  { player: 'Katie D', picks: ['Tommy Fleetwood', 'Chris Gotterup', 'Xander Schauffele'] },
  { player: 'The Wrangler', picks: ['Scottie Scheffler', 'Xander Schauffele', 'Robert MacIntyre'] },
  { player: 'Barty', picks: ['Scottie Scheffler', 'Xander Schauffele', 'Rory McIlroy'] },
  { player: 'JB', picks: ['Tommy Fleetwood', 'Xander Schauffele', 'Rory McIlroy'] },
  { player: 'L Adams', picks: ['Scottie Scheffler', 'Collin Morikawa', 'Rory McIlroy'] },
  { player: 'P Mac', picks: ['Scottie Scheffler', 'Collin Morikawa', 'Rory McIlroy'] },
  { player: 'JD Boy', picks: ['Scottie Scheffler', 'Xander Schauffele', 'Viktor Hovland'] },
  { player: 'Enright', picks: ['Scottie Scheffler', 'Chris Gotterup', 'Wyndham Clark'] },
  { player: 'Jonesy', picks: ['Tommy Fleetwood', 'Robert MacIntyre', 'Rory McIlroy'] },
  { player: 'Chalkey', picks: ['Tommy Fleetwood', 'Robert MacIntyre', 'Rory McIlroy'] },
  { player: 'J Tilley', picks: ['Scottie Scheffler', 'Robert MacIntyre', 'Rory McIlroy'] },
  { player: 'Spinetto', picks: ['Scottie Scheffler', 'Hideki Matsuyama', 'Rory McIlroy'] },
  { player: 'Trump H', picks: ['Scottie Scheffler', 'Shane Lowry', 'Brian Harman'] },
  { player: 'Matt B', picks: ['Scottie Scheffler', 'Rory McIlroy', 'Viktor Hovland'] },
  { player: 'Sloanie', picks: ['Scottie Scheffler', 'Rory McIlroy', 'Justin Rose'] },
  { player: 'G Ponting', picks: ['Tommy Fleetwood', 'Viktor Hovland', 'Justin Rose'] },
  { player: 'Kimbo Slice', picks: ['Scottie Scheffler', 'Sungjae Im', 'Matt Fitzpatrick'] },
  { player: 'M Sanders', picks: ['Russell Henley', 'Robert MacIntyre', 'Matt Fitzpatrick'] },
  { player: 'Bradley C', picks: ['Adam Scott', 'Justin Thomas', 'Russell Henley'] },
  { player: 'Nick Fitz', picks: ['Ludvig Åberg', 'Justin Thomas', 'Matt Fitzpatrick'] },
  { player: 'P Lund', picks: ['Russell Henley', 'Justin Rose', 'Brian Harman'] },
  { player: 'Up the Whas', picks: ['Chris Gotterup', 'Xander Schauffele', 'Rory McIlroy'] },
  { player: 'Mal J', picks: ['Chris Gotterup', 'Robert MacIntyre', 'Matt Fitzpatrick'] },
  { player: 'Shaw', picks: ['Xander Schauffele', 'Sungjae Im', 'Ben Griffin'] },
  { player: 'D Haycock', picks: ['Chris Gotterup', 'Sungjae Im', 'Justin Rose'] },
  { player: 'Maccas', picks: ['Collin Morikawa', 'Keith Mitchell', 'Viktor Hovland'] },
  { player: 'Lamming', picks: ['Shane Lowry', 'Rory McIlroy', 'Sepp Straka'] },
  { player: 'T Rowe', picks: ['Shane Lowry', 'Rory McIlroy', 'Justin Rose'] },
  { player: 'AD', picks: ['Rory McIlroy', 'Min Woo Lee', 'Matt Fitzpatrick'] },
  { player: 'H Naka', picks: ['Cameron Young', 'Tommy Fleetwood', 'Akshay Bhatia'] },
  { player: 'M Little', picks: ['Cameron Young', 'Rory McIlroy', 'Matt Fitzpatrick'] },
  { player: 'Nath Ferg', picks: ['Cameron Young', 'Justin Rose', 'Matt Fitzpatrick'] },
  { player: 'Cam P', picks: ['Sam Burns', 'Scottie Scheffler', 'Matt Fitzpatrick'] },
  { player: 'T Coleman', picks: ['Scottie Scheffler', 'Tommy Fleetwood', 'Viktor Hovland'] },
  { player: 'Crusader', picks: ['Scottie Scheffler', 'Tommy Fleetwood', 'Matt Fitzpatrick'] },
  { player: 'Baylis', picks: ['Scottie Scheffler', 'Tommy Fleetwood', 'Justin Rose'] },
  { player: 'Mr Grant', picks: ['Scottie Scheffler', 'Xander Schauffele', 'Matt Fitzpatrick'] },
  { player: 'Brian Irish', picks: ['Scottie Scheffler', 'Rory McIlroy', 'Tom Kim'] },
  { player: 'Muzza T', picks: ['Tommy Fleetwood', 'Rory McIlroy', 'Tom Kim'] },
  { player: 'Pete Holly', picks: ['Scottie Scheffler', 'Rory McIlroy', 'Justin Rose'] },
  { player: 'Timmy S', picks: ['Tommy Fleetwood', 'Rory McIlroy', 'Aaron Rai'] },
  { player: 'Arnie Palmer', picks: ['Scottie Scheffler', 'Rory McIlroy', 'Justin Rose'] },
  { player: 'K McGinness', picks: ['Tommy Fleetwood', 'Rory McIlroy', 'Matt Fitzpatrick'] },
  { player: 'Trent W', picks: ['Tommy Fleetwood', 'Rory McIlroy', 'Matt Fitzpatrick'] },
  { player: 'Wazza SB', picks: ['Scottie Scheffler', 'Rory McIlroy', 'Matt Fitzpatrick'] },
  { player: 'Sir Steve', picks: ['Scottie Scheffler', 'Rory McIlroy', 'Matt Fitzpatrick'] },
  { player: 'T Wallace', picks: ['Tommy Fleetwood', 'Justin Rose', 'Matt Fitzpatrick'] },
  { player: 'Hancock', picks: ['Tommy Fleetwood', 'Rory McIlroy', 'Justin Rose'] },
  { player: 'B Ashford', picks: ['Tommy Fleetwood', 'Justin Rose', 'Matt Fitzpatrick'] },
  { player: 'Barley', picks: ['Tommy Fleetwood', 'Justin Rose', 'Nicolai Højgaard'] },
  { player: 'Nat M', picks: ['Scottie Scheffler', 'Justin Rose', 'Matt Fitzpatrick'] },
  { player: 'J Barbour', picks: ['Tommy Fleetwood', 'Justin Rose', 'Matt Fitzpatrick'] },
  { player: 'Haycock Snr', picks: ['Ludvig Åberg', 'Rory McIlroy', 'Matt Fitzpatrick'] },
  { player: 'D Donnelly', picks: ['Russell Henley', 'Justin Rose', 'Wyndham Clark'] },
  { player: 'Brom', picks: ['Chris Gotterup', 'Rory McIlroy', 'Matt Fitzpatrick'] },
  { player: 'R Fowler', picks: ['Chris Gotterup', 'Rory McIlroy', 'Matt Fitzpatrick'] },
  { player: 'Budgie', picks: ['Collin Morikawa', 'Rory McIlroy', 'Matt Fitzpatrick'] },
  { player: 'Lynda R', picks: ['Xander Schauffele', 'Justin Rose', 'Matt Fitzpatrick'] },
  { player: 'John Edge', picks: ['Collin Morikawa', 'Justin Rose', 'Tom Kim'] },
  { player: 'P Langley', picks: ['Robert MacIntyre', 'Rory McIlroy', 'Matt Fitzpatrick'] },
  { player: 'A Bull', picks: ['Robert MacIntyre', 'Rory McIlroy', 'Wyndham Clark'] },
  { player: 'D Tucker', picks: ['Robert MacIntyre', 'Rory McIlroy', 'Matt Fitzpatrick'] },
  { player: 'D McCarthy', picks: ['Robert MacIntyre', 'Matt Fitzpatrick', 'Viktor Hovland'] },
  { player: 'Mr Manson', picks: ['Robert MacIntyre', 'Tom Kim', 'Matt Fitzpatrick'] },
  { player: 'R McKnight', picks: ['Robert MacIntyre', 'Sepp Straka', 'Matt Fitzpatrick'] },
  { player: 'Kitch', picks: ['Rory McIlroy', 'Tom Kim', 'Matt Fitzpatrick'] },
  { player: 'Doc Campbell', picks: ['Rory McIlroy', 'Wyndham Clark', 'Matt Fitzpatrick'] },
  { player: 'K Ferg', picks: ['Justin Rose', 'Matt Fitzpatrick', 'Viktor Hovland'] },
];
