// Central tournament setup.
// To trial another event, change this file plus your Vercel env vars:
// SLASH_GOLF_TOURN_ID, SLASH_GOLF_YEAR, TOURNAMENT_STATE_ID.

export const tournamentConfig = {
  majorLabel: '91ST MASTERS TOURNAMENT',
  title: 'MASTERS PICK 3 LIVE',
  venue: 'Augusta National Golf Club',
  location: 'Augusta, Georgia',
  dates: 'April 8–11, 2027',
  prizePool: '$1,800',
  tournamentTimezone: 'America/New_York',
  jackpotRule: 'To win, your picks must include the Masters Champion. If no punter selects them, the prize pool jackpots.',
  heroImage: '/masters-amen-corner.svg'
};

export const poolEntries = [
  { player: 'Barty', picks: ['Ben Griffin', 'Max Homa', 'Tom Kim'] },
  { player: 'Enright', picks: ['Tony Finau', 'Jordan Spieth', 'J.T. Poston'] },
  { player: 'Roche SES', picks: ['Sungjae Im', 'Davis Thompson', 'Keith Mitchell'] },
  { player: 'Kitch', picks: ['Max Homa', 'Keegan Bradley', 'Chris Gotterup'] },
  { player: 'Brom', picks: ['Tom Kim', 'Ben Griffin', 'Taylor Pendrith'] },
  { player: 'Shaw', picks: ['Jordan Spieth', 'Rickie Fowler', 'Lucas Glover'] },
  { player: 'Brian Irish', picks: ['Tony Finau', 'Sungjae Im', 'Max Homa'] },
  { player: 'Jonesy', picks: ['Tom Kim', 'Davis Thompson', 'Ben Griffin'] },
  { player: 'Haycock Snr', picks: ['Keith Mitchell', 'Mackenzie Hughes', 'Adam Svensson'] },
  { player: 'Mal J', picks: ['J.T. Poston', 'Tom Hoge', 'Andrew Novak'] },
  { player: 'Doc Campbell', picks: ['Tony Finau', 'Max Homa', 'Ben Griffin'] },
  { player: 'T Coleman', picks: ['Sungjae Im', 'Tom Kim', 'Keegan Bradley'] },
  { player: 'A Rose', picks: ['Jordan Spieth', 'Davis Thompson', 'Taylor Pendrith'] },
  { player: 'D Haycock', picks: ['Max Homa', 'Rickie Fowler', 'Keith Mitchell'] },
  { player: 'P Langley', picks: ['Tony Finau', 'J.T. Poston', 'Lucas Glover'] },
  { player: 'T Wallace', picks: ['Tom Kim', 'Ben Griffin', 'Chris Gotterup'] },
  { player: 'K Ferg', picks: ['Sungjae Im', 'Taylor Pendrith', 'Adam Svensson'] },
  { player: 'JB', picks: ['Jordan Spieth', 'Max Homa', 'Davis Thompson'] },
  { player: 'D McCarthy', picks: ['Tom Kim', 'Keith Mitchell', 'Andrew Novak'] },
  { player: 'Nath Ferg', picks: ['Tony Finau', 'Keegan Bradley', 'Tom Hoge'] },
  { player: 'Muzza T', picks: ['Sungjae Im', 'Ben Griffin', 'Rickie Fowler'] },
  { player: 'D Donnelly', picks: ['Max Homa', 'J.T. Poston', 'Mackenzie Hughes'] },
  { player: 'Hancock', picks: ['Jordan Spieth', 'Tom Kim', 'Lucas Glover'] },
  { player: 'B Ashford', picks: ['Tony Finau', 'Davis Thompson', 'Chris Gotterup'] },
  { player: 'Bradley C', picks: ['Ben Griffin', 'Keegan Bradley', 'Taylor Pendrith'] },
  { player: 'Sloanie', picks: ['Sungjae Im', 'Max Homa', 'Keith Mitchell'] },
  { player: 'R Fowler', picks: ['Jordan Spieth', 'J.T. Poston', 'Adam Svensson'] },
  { player: 'Sparky', picks: ['Tom Kim', 'Rickie Fowler', 'Andrew Novak'] },
  { player: 'Barley', picks: ['Tony Finau', 'Ben Griffin', 'Davis Thompson'] },
  { player: 'Pete Holly', picks: ['Max Homa', 'Taylor Pendrith', 'Tom Hoge'] },
  { player: 'Timmy S', picks: ['Sungjae Im', 'Jordan Spieth', 'Chris Gotterup'] },
  { player: 'Mr Grant', picks: ['Tom Kim', 'Keegan Bradley', 'Lucas Glover'] },
  { player: 'Greg B', picks: ['Tony Finau', 'Keith Mitchell', 'Mackenzie Hughes'] },
  { player: 'JD Boy', picks: ['Ben Griffin', 'J.T. Poston', 'Rickie Fowler'] },
  { player: 'Mr Manson', picks: ['Max Homa', 'Davis Thompson', 'Adam Svensson'] },
  { player: 'Up the Wahs', picks: ['Sungjae Im', 'Tom Kim', 'Taylor Pendrith'] },
  { player: 'G Ponting', picks: ['Jordan Spieth', 'Keegan Bradley', 'Andrew Novak'] },
  { player: 'R McKnight', picks: ['Tony Finau', 'Max Homa', 'Keith Mitchell'] },
  { player: 'Chalkey', picks: ['Ben Griffin', 'Lucas Glover', 'Tom Hoge'] },
  { player: 'Budgie', picks: ['Tom Kim', 'Davis Thompson', 'Mackenzie Hughes'] },
  { player: 'Lamming', picks: ['Sungjae Im', 'J.T. Poston', 'Rickie Fowler'] },
  { player: 'A Bull', picks: ['Jordan Spieth', 'Tony Finau', 'Chris Gotterup'] },
  { player: 'Lynda R', picks: ['Max Homa', 'Ben Griffin', 'Adam Svensson'] },
  { player: 'Cam P', picks: ['Tom Kim', 'Taylor Pendrith', 'Keith Mitchell'] },
  { player: 'Wazza SB', picks: ['Sungjae Im', 'Keegan Bradley', 'Davis Thompson'] },
  { player: 'Mac The Knife', picks: ['Andrew Novak', 'Mackenzie Hughes', 'Tom Hoge'] },
  { player: 'Crusader', picks: ['Tony Finau', 'Tom Kim', 'Max Homa'] },
  { player: 'Maccas', picks: ['Ben Griffin', 'Lucas Glover', 'Rickie Fowler'] },
  { player: 'Matt B', picks: ['Jordan Spieth', 'Sungjae Im', 'J.T. Poston'] },
  { player: 'The Wrangler', picks: ['Tony Finau', 'Davis Thompson', 'Taylor Pendrith'] },
  { player: 'AD', picks: ['Max Homa', 'Keith Mitchell', 'Chris Gotterup'] },
  { player: 'J Turner', picks: ['Tom Kim', 'Ben Griffin', 'Adam Svensson'] },
  { player: 'M Sanders', picks: ['Sungjae Im', 'Jordan Spieth', 'Andrew Novak'] },
  { player: 'Nick Fitz', picks: ['Tony Finau', 'J.T. Poston', 'Mackenzie Hughes'] },
  { player: 'T Rowe', picks: ['Max Homa', 'Keegan Bradley', 'Lucas Glover'] },
  { player: 'J Tilley', picks: ['Tom Kim', 'Davis Thompson', 'Rickie Fowler'] },
  { player: 'Arnie Palmer', picks: ['Ben Griffin', 'Taylor Pendrith', 'Tom Hoge'] },
  { player: 'Kimbo Slice', picks: ['Sungjae Im', 'Keith Mitchell', 'Chris Gotterup'] },
  { player: 'L Adams', picks: ['Jordan Spieth', 'Max Homa', 'Andrew Novak'] },
  { player: 'K McGinness', picks: ['Tony Finau', 'Tom Kim', 'Ben Griffin'] },
  { player: 'Baylis', picks: ['Davis Thompson', 'J.T. Poston', 'Adam Svensson'] },
  { player: 'D Tucker', picks: ['Sungjae Im', 'Keegan Bradley', 'Keith Mitchell'] },
  { player: 'Kev Martin', picks: ['Max Homa', 'Jordan Spieth', 'Taylor Pendrith'] },
  { player: 'P Mac', picks: ['Tom Kim', 'Lucas Glover', 'Mackenzie Hughes'] },
  { player: 'J Barbour', picks: ['Tony Finau', 'Ben Griffin', 'Rickie Fowler'] },
  { player: 'P Lund', picks: ['Sungjae Im', 'Davis Thompson', 'Tom Hoge'] },
  { player: 'Trump H', picks: ['Max Homa', 'J.T. Poston', 'Chris Gotterup'] },
  { player: 'John Edge', picks: ['Jordan Spieth', 'Keith Mitchell', 'Andrew Novak'] },
  { player: 'Trent W', picks: ['Tom Kim', 'Keegan Bradley', 'Adam Svensson'] },
  { player: 'Sir Steve', picks: ['Tony Finau', 'Max Homa', 'Lucas Glover'] },
  { player: 'Nat M', picks: ['Sungjae Im', 'Ben Griffin', 'Taylor Pendrith'] },
  { player: 'Spinetto', picks: ['Jordan Spieth', 'Tom Kim', 'Davis Thompson'] }
];
